import { Inter } from "next/font/google";
import "./globals.css";
import "@/assets/css/sidebar.css";
import "@/assets/css/nav.css";
import "@/assets/css/home.css";
import "@/assets/css/bootstrap.min.css";
import "@/assets/css/responsive.css";
import "@/assets/css/variable.css";
import "@/assets/css/detail.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "VacationRentals",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css"
        />
      </head>
      <body className={inter.className}>{children}</body>
      {/* <script src="assets/js/jquery.min.js"></script>
      <script src="assets/js/bootstrap.bundle.min.js"></script>
      <script src="assets/js/script.js"></script> */}
    </html>
  );
}
