"use client";
// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };
import Sidebar from "@/app/Sidebar/sidebar";
import Topbar from "@/app/Topbar/Topbar";

export default function RootLayout({ children }) {
  return (
    <>
      {/* <Sidebar /> */}
      {/* <main> */}
      {/* <Topbar onToggleSidebar={() => setIsOpenSidebar((is) => !is)} /> */}

      <div className="dashboard">{children}</div>
      {/* </main> */}
    </>
  );
}
